"""empty message

Revision ID: 974d7c458a0e
Revises: 
Create Date: 2017-12-14 21:58:46.564086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974d7c458a0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('unique_id', 'email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('campaign',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('stages', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('email',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    op.drop_table('campaign')
    op.drop_table('user')
    # ### end Alembic commands ###
